// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsvtrbfvpaqdpvzzngci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzdnRyYmZ2cGFxZHB2enpuZ2NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDAzMzcsImV4cCI6MjA2NTExNjMzN30.hVxzHJGxunBmlOcHcAiie3mBp48Lep0hdfUjlB5gH1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);